services:
  app:
      image: streamlit:latest
      container_name: streamlit_loans
      build: ./docker/web
      command: streamlit run app/main.py --server.port 8502 --server.address 0.0.0.0 
      volumes:
       - ./:/usr/src/app
      ports:
            - 8502:8502
      depends_on:
        clickhouse-server:
          condition: service_healthy
          restart: true
      networks:
        - click-streamlit

  clickhouse-server:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse_loans 
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
    volumes:
      - ./data:/var/lib/clickhouse/
      - ./logs:/var/log/clickhouse-server/
      - ./config/:/etc/clickhouse-server/config/
      - ./users/:/etc/clickhouse-server/users.d/
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    healthcheck:
      test: wget --no-verbose --tries=1 http://127.0.0.1:8123/ping || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - click-streamlit

networks:
  click-streamlit:
    name: click-streamlit
    driver: bridge 

